version: '2'

services:
  frontend:
    build: 
      context: ./MediQA-Frontend/
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - default
  backend:
    build: 
      context: ./MediQA-Backend/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    networks:
      - default
volumes:
  db_data:
networks:
  default:
    driver: bridge